# Generated by Django 4.2 on 2024-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SwapEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("account_address", models.CharField(max_length=44)),
                ("timestamp", models.DateTimeField()),
                ("token_in_mint", models.CharField(max_length=50)),
                (
                    "token_in_amount",
                    models.DecimalField(decimal_places=9, max_digits=20),
                ),
                ("token_out_mint", models.CharField(max_length=50)),
                (
                    "token_out_amount",
                    models.DecimalField(decimal_places=9, max_digits=20),
                ),
                ("raw_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="swapevent",
            index=models.Index(
                fields=["transaction_id"], name="track_acoun_transac_f78e02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swapevent",
            index=models.Index(
                fields=["account_address"], name="track_acoun_account_19abdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swapevent",
            index=models.Index(
                fields=["timestamp"], name="track_acoun_timesta_7dd365_idx"
            ),
        ),
    ]
